chore: msa 배포5차

diff --git a/.github/workflows/deploy-server-with-compose.yml b/.github/workflows/deploy-server-with-compose.yml
--- a/.github/workflows/deploy-server-with-compose.yml
+++ b/.github/workflows/deploy-server-with-compose.yml
@@ -59,12 +59,12 @@ jobs:
           username: ubuntu
           key: ${{ secrets.EC2_PEMKEY }}
           script: |
-                    if ! type docker > /dev/null ; then
-                    sudo snap install docker || echo "docker install failed"
-                    fi 
-                    sudo docker login --username ${{ secrets.DOCKER_EMAIL }} --password ${{ secrets.DOCKER_PASSWORD }}
-                    
-                    sudo docker-compose pull && sudo docker-compose up -d
+            if ! type docker > /dev/null ; then
+            sudo snap install docker || echo "docker install failed"
+            fi 
+            sudo docker login --username ${{ secrets.DOCKER_EMAIL }} --password ${{ secrets.DOCKER_PASSWORD }}
+            
+            sudo docker-compose pull && sudo docker-compose up -d
             
             # 사용되지 않은 도커 이미지 삭제
-                    sudo docker image prune -f
+            sudo docker image prune -f
